name: social_media_app
description: A social media app using Flutter, Dart, GetX, and REST API that allows users to share their photos and videos.

publish_to: "none"

version: 1.0.1+31

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0

  talker_flutter: ^3.3.1

  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  photo_view: ^0.14.0
  cached_network_image: ^3.3.0
  fast_cached_network_image: ^1.2.0
  flutter_carousel_widget: ^2.1.0

  flutter_animate: ^4.2.0+1
  # rive: ^0.11.3

  connectivity_plus: ^4.0.2
  intl: ^0.18.1
  get_time_ago: ^1.2.5

  dio: ^5.3.3
  http: ^1.1.0

  cloudinary: ^1.2.0
  r_upgrade: ^0.4.2

  libsignal_protocol_dart: ^0.7.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  url_launcher: ^6.1.14
  flutter_linkify: ^6.0.0
  share_plus: ^7.1.0

  flutter_local_notifications: ^15.1.1
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8

  # better_player: ^0.0.83
  video_player: ^2.7.2
  video_editor: ^3.0.0
  just_audio: ^0.9.35

  emoji_picker_flutter: ^1.6.1
  path: ^1.8.3
  file_picker: ^5.5.0
  path_provider: ^2.1.1
  flutter_markdown: ^0.6.17+4
  flutter_image_compress: ^2.0.4
  video_compress_ds: ^3.1.6

  flutter_screenutil: ^5.9.0
  permission_handler: ^11.0.0
  flutter_datetime_picker: ^1.5.1

  # State Management
  flutter_bloc: ^8.1.3

  get: ^4.6.6
  get_storage: ^2.1.1
  built_value: ^8.6.3
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  copy_with_extension: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3

  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/rive/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Muge
      fonts:
        - asset: assets/fonts/MugeRegular.ttf
